name: Check INPE STAC API compatibility

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run code to check STAC API connection
        run: |
          python -m pip install --upgrade pip
          pip install cbers4asat

          python3 -c \
          'from cbers4asat import Cbers4aAPI;\
          api = Cbers4aAPI();\
          p = api.query_by_id(scene_id="CBERS4A_WPM22912420210830", collection="CBERS4A_WPM_L4_DN");\
          print(p)'

          python3 -c \
          'from cbers4asat import Cbers4aAPI;\
          from datetime import date;\
          api = Cbers4aAPI();\
          p = api.query(location=(229, 124),\
               initial_date=date(2023, 8, 25),\
               end_date=date.today(),\
               cloud=100,\
               limit=100,\
               collections=["CBERS4A_WPM_L4_DN"]);\
          print(p)'
